// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "WWB Template 10", "      WWB Template 10                            Sazu Assam Tutorials                  The First Message  &quot Work hard believe in   yourself and Success   will come forward&quot       Welcome              The Second   Message  I am so glad you   asked for helped   when needed it.      The Third   Message  Believe in Yourself,   You Can Do it.            Home    About&nbsp Us    Services    Solutions    Support    Contact              Assam Higher Secondary Education Counsil  AHSEC 2015 To 2020 Solved Question Papers     Board of Secondary Education Assam  SEBA 2015 To 2020 Solved Question Papers     Universities Of Assam,India2015 To 2020 Solved Question Papers     Coming Soon      &quot I understand the Walls Outside of this Websites and think about Your Future,Welcome to Correct Place&quot                 Use home always for use all menu                  Copyright © 2020 by &quot Sazu Assam Tutorials&quot &nbsp  ·&nbsp  All Rights reserved&nbsp           ", "");
   this[database_length++] = new SearchPage("About_Us.html", "About Us", "        About Us                    Sazu Assam Tutorials              Home    About&nbsp Us    Services    Solutions    Support    Contact                  The First Message  &quot Work hard believe in   yourself and Success   will come forward&quot       The Second   Message  I am so glad you   asked for helped   when needed it.      The Third   Message  Believe in Yourself,   You Can Do it.                  Copyright © 2020 by &quot Sazu Assam Tutorials&quot &nbsp  ·&nbsp  All Rights reserved&nbsp          About Us    E-Mail Address = mrsrtraders@gmail.com         ", "");
   this[database_length++] = new SearchPage("Services.html", "Services", "        Services                Sazu Assam Tutorials              Home    About&nbsp Us    Services    Solutions    Support    Contact                  The First Message  &quot Work hard believe in   yourself and Success   will come forward&quot       The Second   Message  I am so glad you   asked for helped   when needed it.      The Third   Message  Believe in Yourself,   You Can Do it.              Copyright © 2020 by &quot Sazu Assam Tutorials&quot &nbsp  ·&nbsp  All Rights reserved&nbsp          Copyright © 2020 by &quot Sazu Assam Tutorials&quot &nbsp  ·&nbsp  All Rights reserved&nbsp              Services    Assam Higher Secondary Education Counsil  AHSEC 2015 To 2020 Solved Question Papers       Board of Secondary Education Assam  SEBA 2015 To 2020 Solved Question Papers       Universities Of Assam,India2015 To 2020 Solved Question Papers       Coming Soon       ", "");
   this[database_length++] = new SearchPage("Solutions.html", "Untitled Page", "        Untitled Page                Sazu Assam Tutorials              Home    About&nbsp Us    Services    Solutions    Support    Contact                  The First Message  &quot Work hard believe in   yourself and Success   will come forward&quot       The Second   Message  I am so glad you   asked for helped   when needed it.      The Third   Message  Believe in Yourself,   You Can Do it.              Copyright © 2020 by &quot Sazu Assam Tutorials&quot &nbsp  ·&nbsp  All Rights reserved&nbsp               &#9632      All Mathamatics Formula         &#9632      All SEBA CLASS 10 Mathamatics Solution         &#9632      All AHSEC COMMERCE Solution         &#9632      All AHSEC IMPORTANT Solution        Solutions    COMING SOON     ", "");
   this[database_length++] = new SearchPage("Support.html", "Untitled Page", "        Untitled Page                Sazu Assam Tutorials              Home    About&nbsp Us    Services    Solutions    Support    Contact              The First Message  &quot Work hard believe in   yourself and Success   will come forward&quot       The Second   Message  I am so glad you   asked for helped   when needed it.      The Third   Message  Believe in Yourself,   You Can Do it.      Support                                Your One Rupees of Donation,A Kid Can Go to School                Copyright © 2020 by &quot Sazu Assam Tutorials&quot &nbsp  ·&nbsp  All Rights reserved&nbsp           ", "");
   this[database_length++] = new SearchPage("Contact.html", "Untitled Page", "        Untitled Page                        Sazu Assam Tutorials              Home    About&nbsp Us    Services    Solutions    Support    Contact              The First Message  &quot Work hard believe in   yourself and Success   will come forward&quot       The Second   Message  I am so glad you   asked for helped   when needed it.      The Third   Message  Believe in Yourself,   You Can Do it.                  Copyright © 2020 by &quot Sazu Assam Tutorials&quot &nbsp  ·&nbsp  All Rights reserved&nbsp             Email   mrsrtraders@gmail.com       Coming Soon  &nbsp  Coming Soon      &nbsp  Coming Soon  &nbsp  Coming Soon         ", "");
   return this;
}
